package br.com.partiu.modelo;
// Generated Feb 26, 2016 2:18:19 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Avalia generated by hbm2java
 */
@Entity
@Table(name = "avalia", catalog = "partiu")
public class Avalia implements java.io.Serializable {

	private Integer id;
	private Estabelecimento estabelecimento;
	private String comentario;
	private Integer estrelas;

	public Avalia() {
	}

	public Avalia(Estabelecimento estabelecimento, String comentario, Integer estrelas) {
		this.estabelecimento = estabelecimento;
		this.comentario = comentario;
		this.estrelas = estrelas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAvalia")
	public Estabelecimento getEstabelecimento() {
		return this.estabelecimento;
	}

	public void setEstabelecimento(Estabelecimento estabelecimento) {
		this.estabelecimento = estabelecimento;
	}

	@Column(name = "Comentario", length = 300)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "estrelas")
	public Integer getEstrelas() {
		return this.estrelas;
	}

	public void setEstrelas(Integer estrelas) {
		this.estrelas = estrelas;
	}

}
