package br.com.partiu.modelo;
// Generated Feb 26, 2016 2:18:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estabelecimento generated by hbm2java
 */
@Entity
@Table(name = "estabelecimento", catalog = "partiu")
public class Estabelecimento implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String telefone;
	private String cnpj;
	private String cep;
	private String logradouro;
	private String numero;
	private String complemento;
	private String estado;
	private String cidade;
	private String especialidade;
	private String diferencial;
	private byte[] imgens;
	private byte[] logoBar;
	private Set<Avalia> avalias = new HashSet<Avalia>(0);
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Estabelecimento() {
	}

	public Estabelecimento(String nome, String telefone, String cnpj, String cep, String logradouro, String numero,
			String complemento, String estado, String cidade, String especialidade, String diferencial, byte[] imgens,
			byte[] logoBar, Set<Avalia> avalias, Set<Reserva> reservas) {
		this.nome = nome;
		this.telefone = telefone;
		this.cnpj = cnpj;
		this.cep = cep;
		this.logradouro = logradouro;
		this.numero = numero;
		this.complemento = complemento;
		this.estado = estado;
		this.cidade = cidade;
		this.especialidade = especialidade;
		this.diferencial = diferencial;
		this.imgens = imgens;
		this.logoBar = logoBar;
		this.avalias = avalias;
		this.reservas = reservas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Nome", length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Telefone", length = 9)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "CNPJ", length = 19)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "CEP", length = 9)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "Logradouro", length = 200)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "Numero", length = 10)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "Complemento", length = 200)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "Estado", length = 30)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "Cidade", length = 30)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "Especialidade", length = 20)
	public String getEspecialidade() {
		return this.especialidade;
	}

	public void setEspecialidade(String especialidade) {
		this.especialidade = especialidade;
	}

	@Column(name = "Diferencial", length = 30)
	public String getDiferencial() {
		return this.diferencial;
	}

	public void setDiferencial(String diferencial) {
		this.diferencial = diferencial;
	}

	@Column(name = "Imgens")
	public byte[] getImgens() {
		return this.imgens;
	}

	public void setImgens(byte[] imgens) {
		this.imgens = imgens;
	}

	@Column(name = "Logo_bar")
	public byte[] getLogoBar() {
		return this.logoBar;
	}

	public void setLogoBar(byte[] logoBar) {
		this.logoBar = logoBar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estabelecimento")
	public Set<Avalia> getAvalias() {
		return this.avalias;
	}

	public void setAvalias(Set<Avalia> avalias) {
		this.avalias = avalias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estabelecimento")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
